[alias]
bundle = "run -p perspective-bundle"

[build]
rustflags = ["--cfg=web_sys_unstable_apis", "-Csymbol-mangling-version=v0"]
# rustflags = [
#     "--cfg=web_sys_unstable_apis",
#     "--cfg=pyo3_disable_reference_pool",
#     "-Csymbol-mangling-version=legacy",
#     "-Zunstable-options",
# ]
target-dir = "rust/target"

[target.wasm32-unknown-unknown]
rustflags = [
    "--cfg=getrandom_backend=\"wasm_js\"",
    "--cfg=web_sys_unstable_apis",
    "-Ctarget-feature=+bulk-memory,+simd128,+relaxed-simd,+reference-types",
]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static", "--cfg=web_sys_unstable_apis"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static", "--cfg=web_sys_unstable_apis"]

[future-incompat-report]
frequency = 'never'

[unstable]
bindeps = true

[term]
quiet = false
verbose = false
color = 'always'
